try {
  console.log("1");
  console.log(data);
  console.log("3");
} catch (err) {
  console.log("에러발생");
}
